[package]
name = "tls-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.21"}
s2n-tls = "0.3"
s2n-tls-tokio = "0.3"
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.24"
webpki-roots = "0.25"
rcgen = "0.11"
rustls-pemfile = "1.0"
